### ISSUE TITLE
Bad link in "Rust Bursts" RSS feed

### ISSUE THREAD

**Issue by jimblandy** [bluss/bluss.github.io#1]
When I visit https://bluss.github.io/feed.xml directly, the permalinks to individual blog posts lead to a 404 from github.io.

In the feed.xml file, I see the following structure:

```
<rss>
  <channel>
    <title>bluss' rust bursts</title>
    ...
    <item>
      <title>Control Flow for Visitor Callbacks</title>
      ...
      <link>https://github.com/bluss//rust/2016/10/17/control-flow-for-visitors/</link>
```

That link is broken.

**Comment by bluss** [comment]
Thanks! I think it's fixed now, I didn't have the correct url configured. I'm also now subscribed to my own blog... so that I know it works. :smile:

**Comment by jimblandy** [comment]
Good idea! LOL

Thanks!
